# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    volumes:
      - ../data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ../api/prisma/.env

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 5002:8080

  api:
    container_name: api
    restart: on-failure
    build:
      context: ../api
      args:
        - NODE_ENV=development
    ports:
      - 5001:5001
    depends_on:
      - db
    env_file:
      - ../api/.env
    environment:
      - PRODUCTION=false


  # web:
  #   container_name: web
  #   build:
  #     context: ../web
  #     args:
  #       - NODE_ENV=development
  #   ports:
  #     - 6000:80
  #   environment:
  #     - PRODUCTION=false
